name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linting-Formating-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
    name: Python ${{ matrix.python-version }} - Linting, Formatting and Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            
      - name: Install Poetry
        run: |
            pip install poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v4.2.4
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-${{ matrix.python-version }}-
            
      - name: Poetry Config
        run: |
          poetry config virtualenvs.in-project true
            
      - name: Install dependencies
        run: |
          poetry install --no-interaction --all-groups
      
      - name: Ruff linting and formatting
        run: |
          poetry run ruff check .
          poetry run ruff format --check .
    
      - name: Run tests with pytest
        run: |
          poetry run pytest